import './globals.css'
import './home.scss'
import { Open_Sans } from 'next/font/google'
import Header from '../components/header/Header'
import Footer from '../components/footer/Footer'

const font = Open_Sans({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={font.className}>
        <Header name="Home"/>
        {children}
        <Footer/>
      </body>
    </html>
  )
}
