import React from 'react';
import './globals.css';
import './home.scss';
import { Open_Sans } from 'next/font/google';
import MainPanel from '../components/mainpanel/MainPanel';
import Footer from '../components/footer/Footer';
import SimpleBottomNavigation from '../components/navbar/Navbar';
import Navbar from '../components/navbar/Navbar';

const font = Open_Sans({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap" />
      </head>
      <body className={font.className}>
        
        <MainPanel name="Home" />
        {children}

        {/*navbar Mobile in basso*/}
        <SimpleBottomNavigation name="NavbarF"/>
        
      </body>
    </html>
  );
}
